version: '3.8'
services:
    web:
        container_name: mcwebsite
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 5002:80
            - 25566:25566
        volumes:
            - /var/minecraft:/var/minecraft