version: '3.8'
services:
    web:
        image: brandonrs/mcwebsite
        container_name: mcwebsite
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 5002:5002
            - 25566:25566
        volumes:
            - /var/minecraft:/var/minecraft
        restart: unless-stopped
